# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17o_OLuLYtiQcTUkRJNEfjWZY_HKrJHyy
"""

marks =89.5

print(marks)

students=50

print(students)

name ="CHATHA"

print(name)

num1=10
num2=20
print(num1+num2)

lenght=15.25
width=20.6
area=lenght*width
print(area)

a=10
b=20
c=30
a,b,c=b,c,a
print(a,b,c)

a=30
b=40
a,b=b,a
print(a,b)

"""String is used in sigle quote or double quotes '',""
"""

print("HELLO WORLD")

"""ASSIGNING A STRING TO A VARIABLE"""

a="HELLO WORLD"
print(a)

"""MULTILINE STRING
WRITTEN IN ''' TRIPPLE QUOTES
"""

a="""CHATHA IA A PLAYER.HE PLAYS FOOTBALL FOR THE SAUDI ARABIA"""
print(a)

"""UPPER() CASE"""

a="hello world"
print(a.upper())

"""LOWER() CASE"""

a="CHATHA"
print(a.lower())

"""REMOVE WHITE SPACES
strip()
"""

a=" hello world"
print(a.strip())

"""REPLACE FUNCTION
.replace()
"""

a="chatha"
print(a.replace("c","t"),a.replace("h","o"))

"""SPLIT() FUNCTION"""

a="hi how are you ,i am fine ,what about you"
print(a.split(","))

capitalized_text="chatha"
print(capitalized_text.upper())

lowercase_text="CHATHAAAJEGDYE"
print(lowercase_text.lower())

white_space="                                       chayajndjeyfyeuefu"
print(white_space.strip())

world_space="hello world how are you doing todat what's your plan today"
print(world_space.split())

replaced_text="positive"
a="remarkable"
print(replaced_text.replace("positive",a))

"""LIST START WITH SQUARE BRACKETS []"""

brothers=["talha","nomi","chatha"]
print(brothers)
print(len(brothers))

"""DIFFERENT DATA TYPES"""

list=["apple",10,True]
print(list)

"""TUPLE
tuple is used to store multiple values ia a variable Tuple is written in () brackets. Its value can not be changed
"""

thistuple=("car","bus","truck")
print(thistuple)

"""SET is created in {} brackets it is unchangeable have no index no dublicate"""

thisset={1,2,3,4}
print(thisset)
print(len(thisset))
print(type(thisset))

"""PYTHON DICTIONARIES Are labeled items not doblicated"""

#installing required modules
!pip install transformers
!pip install datasets

#Text Classification Using Hugging face builtin pipeline

#Sentiment Analysis
import transformers
from transformers import pipeline
pipe = pipeline("text-classification")
pipe("The sky is blue which is absolutely magical")

# Pipeline for text classification
pipe =pipeline("sentiment-analysis")
pipe(["this resturant is awesome","this resturant is awful"])

#Text Summarization
input_text = ("Football is a globally popular sport played between two teams of 11 players. Known for its fast pace, skillful play, and teamwork, it captivates millions. The objective is to score by getting the ball into the opponent's goal. Passion for football unites diverse cultures and nations worldwide.")
print(input_text)

#use bart in pytorch
summarizer = pipeline("summarization")
summarizer("Football is a globally popular sport played between two teams of 11 players. Known for its fast pace, skillful play, and teamwork, it captivates millions. The objective is to score by getting the ball into the opponent's goal. Passion for football unites diverse cultures and nations worldwide.", min_length=5, max_length=15)